### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by joll05** [johnBuffer/NoCol#4]
There is currently no license in this repository. Without a license, standard copyright laws apply and nobody else can use, modify, distribute the code in this repository without explicit permission (see https://choosealicense.com/no-permission/).

It would be great if you were to add a license that specifies what we can and can't do with this code.

**Comment by nuggetofwisdom** [comment]
Hippety hoppety your non-licensed code is now my property

**Comment by johnBuffer** [comment]
Thanks for this remark, just added a MIT license
